spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: user-data-service
  datasource:
    url: jdbc:postgresql://postgres:5432/news
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 30
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8079/eureka/