version: '3'


services:
  postgres-users:
    image: 'postgres:14-alpine'
    container_name: 'postgres-users'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=users
    volumes:
      - ./docker/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  postgres-news:
    image: 'postgres:14-alpine'
    container_name: 'postgres-news'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=news
    volumes:
      - ./docker/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  redis-users:
    container_name: 'redis-users'
    image: 'redis:7-alpine'
    ports:
      - "6379:6379"

  redis-news:
    container_name: 'redis-news'
    image: 'redis:7-alpine'
    ports:
      - "6380:6379"

  liquibase:
    image: 'liquibase/liquibase'

  eureka-server:
    build: ./eureka-server
    container_name: 'eureka-server'
    ports:
      - 8079:8079

  user-data-service:
    build: ./user-data-service
    container_name: 'user-data-service'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-users:5432/users
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8079/eureka
    ports:
      - 8081:8081
    depends_on:
      - postgres-users
      - liquibase
      - eureka-server

  user-service:
    build: ./user-service
    container_name: 'user-service'
    environment:
      - SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_USER-DATA-SERVICE_URL=http://user-data-service:8081
      - SPRING_CACHE_TYPE=REDIS
      - SPRING_DATA_REDIS_URL=redis://redis-users:6379
    ports:
      - 8090:8090
    depends_on:
      - user-data-service
      - redis-users

  user-auth-service:
    build: ./user-authentication-service
    container_name: 'user-auth-service'
    environment:
      - SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_USER-DATA-SERVICE_URL=http://user-data-service:8081
    ports:
      - 8091:8091
    depends_on:
      - user-data-service

  news-data-service:
    build: ./news-data-service
    container_name: 'news-data-service'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-news:5432/news
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8079/eureka
    ports:
      - 8082:8082
    depends_on:
      - postgres-news
      - liquibase
      - eureka-server

  news-service:
    build: ./news-service
    container_name: 'news-service'
    environment:
      - SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_USER-DATA-SERVICE_URL=http://user-data-service:8081
      - SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_NEWS-DATA-SERVICE_URL=http://news-data-service:8082
      - SPRING_CACHE_TYPE=REDIS
      - SPRING_DATA_REDIS_URL=redis://redis-news:6379
    ports:
      - 8080:8080
    depends_on:
      - news-data-service
      - redis-news
