spring:
  application:
    name: news-service
server:
  port: 8080

jwt:
  access:
    secret: 39EhCCpO0YTlfETjF94nwOfa9Q5ls9nwQxy7yeI4ftAipRnyhWFwm
  refresh:
    secret: eijlSaysX8yEsJ4a2yVIdOQ6euYO99QQ3uT5hg4ILcZpAvgdJlF