-- liquibase formatted sql

-- changeset fill tables:add data

INSERT INTO news (user_id, title, "text")
VALUES
	(2, 'Oil found in Belarus', 'Scientists of the National Academy of Sciences found oil deposits'),
	(2, 'Belarusian Hi-Tech Park ranks first in the world in terms of software development', 'Last year, the domestic high-tech park ranked first in the world in terms of software production. The total share of the fleet in the global volume of software production was 18 percent'),
	(2, 'The share of unmanned vehicles in Belarus has reached a record level', 'The share of unmanned vehicles in Belarus has reached 80 percent. Four out of five cars are able to move on Belarusian roads without human intervention'),
	(2, 'The largest 3D printer was assembled in Belarus', 'Belarusian scientists, together with industry representatives, assembled the largest 3D printer in the world'),

	(3, 'GDP per capita increased slightly over the past year', 'At the end of last year, gross domestic product per capita increased by 5 percent and in absolute terms amounted to $115,000'),
	(3, 'The largest 3D printer printed a space rocket', 'The largest 3D printer assembled yesterday printed a space rocket in 2 hours, which will go on a mission to Neptune tomorrow'),
	(3, 'Subway built in Belarus in three days', 'In Krichev, a subway was built in three days, 270 kilometers long, including 91 stations'),
	(3, 'Good news', 'Good event happened in Belarus'),

	(4, 'Good news', 'Good event happened in Belarus'),
	(4, 'Good news', 'Good event happened in Belarus'),
	(4, 'Good news', 'Good event happened in Belarus'),
	(4, 'Good news', 'Good event happened in Belarus'),

	(5, 'Good news', 'Good event happened in Belarus'),
	(5, 'Good news', 'Good event happened in Belarus'),
	(5, 'Good news', 'Good event happened in Belarus'),
	(5, 'Good news', 'Good event happened in Belarus'),

    (6, 'Good news', 'Good event happened in the world'),
	(6, 'Good news', 'Good event happened in the world'),
	(6, 'Good news', 'Good event happened in the world'),
	(6, 'Good news', 'Good event happened in the world');


INSERT INTO "comments" (news_id, user_id, "text")
VALUES
	(1, 7, 'Why do we need so many?'),
	(1, 8, 'Cool!!!'),
	(1, 9, 'Cool!!!'),
	(1, 10, 'Cool!!!'),
	(1, 11, 'Cool!!!'),
	(1, 12, 'Cool!!!'),
	(1, 13, 'Cool!!!'),
	(1, 14, 'Cool!!!'),
	(1, 15, 'Cool!!!'),
	(1, 16, 'Cool!!!'),

	(2, 7, 'Well done boys!!!'),
	(2, 7, 'They work miracles!'),
	(2, 7, 'I repeat, they work miracles!'),
	(2, 8, 'They work miracles!'),
	(2, 9, 'They work miracles!'),
	(2, 10, 'They work miracles!'),
	(2, 11, 'They work miracles!'),
	(2, 12, 'They work miracles!'),
	(2, 14, 'They work miracles!'),
	(2, 15, 'The best!'),

	(3, 12, 'Soon it will be 100%!'),
	(3, 8, 'Mike''s best article!'),
	(3, 9, 'Good news!'),
	(3, 11, 'Good news!'),
	(3, 16, 'Good news!'),
	(3, 16, 'Good news!'),
	(3, 7, 'Good news!'),
	(3, 7, 'Good news!'),
	(3, 10, 'Good news!'),
	(3, 12, 'Good news!'),

    (4, 9, 'The main world news this year!'),
	(4, 14, 'They say that the rocket will be printed...'),
	(4, 16, 'I heard that too!'),
	(4, 14, 'I heard that too!'),
	(4, 12, 'I heard that too!'),
	(4, 10, 'I heard that too!'),
	(4, 13, 'I heard that too!'),
	(4, 15, 'I heard that too!'),
	(4, 11, 'I heard that too!'),
	(4, 9, 'I heard that too!'),

    (5, 9, 'The main world news this year!'),
	(5, 14, 'They say that the rocket will be printed...'),
	(5, 16, 'I heard that too!'),
	(5, 14, 'I heard that too!'),
	(5, 12, 'I heard that too!'),
	(5, 10, 'I heard that too!'),
	(5, 13, 'I heard that too!'),
	(5, 15, 'I heard that too!'),
	(5, 11, 'I heard that too!'),
	(5, 9, 'I heard that too!'),

    (6, 12, 'Soon it will be 100%!'),
	(6, 8, 'Mike''s best article!'),
	(6, 9, 'Good news!'),
	(6, 11, 'Good news!'),
	(6, 16, 'Good news!'),
	(6, 16, 'Good news!'),
	(6, 7, 'Good news!'),
	(6, 7, 'Here you go!'),
	(6, 16, 'Fast they are!'),
	(6, 12, 'Good news!'),

	(7, 14, 'Long waited...'),
	(7, 14, 'Long waited...'),
	(7, 14, 'Long waited...'),
	(7, 14, 'Long waited...'),
	(7, 16, 'Yeah, long waited...'),
	(7, 8, 'Long waited...'),
	(7, 7, 'Long waited...'),
	(7, 15, 'Long waited...'),
	(7, 9, 'Long waited...'),
	(7, 10, 'Long waited...'),

    (8, 7, 'Well done boys!!!'),
	(8, 7, 'They work miracles!'),
	(8, 7, 'I repeat, they work miracles!'),
	(8, 8, 'They work miracles!'),
	(8, 9, 'They work miracles!'),
	(8, 10, 'They work miracles!'),
	(8, 11, 'They work miracles!'),
	(8, 12, 'They work miracles!'),
	(8, 14, 'They work miracles!'),
	(8, 15, 'The best!'),

    (9, 7, 'Comments to nine news'),
	(9, 7, 'Comments to nine news'),
	(9, 7, 'Comments to nine news'),
	(9, 8, 'Comments to nine news'),
	(9, 9, 'Comments to nine news'),
	(9, 10,'Comments to nine news'),
	(9, 11,'Comments to nine news'),
	(9, 12,'Comments to nine news'),
	(9, 14,'Comments to nine news'),
	(9, 15,'Comments to nine news'),

    (10, 7, 'Comments to ten news'),
	(10, 7, 'Comments to ten news'),
	(10, 7, 'Comments to ten news'),
	(10, 8, 'Comments to ten news'),
	(10, 9, 'Comments to ten news'),
	(10, 10,'Comments to ten news'),
	(10, 11,'Comments to ten news'),
	(10, 12,'Comments to ten news'),
	(10, 14,'Comments to ten news'),
	(10, 15,'Comments to ten news');


