spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/auth
          jwk-set-uri: http://localhost:8091/auth/certs
  application:
    name: user-service
  cache:
    type: REDIS
server:
  port: 8090
